### ISSUE TITLE
static_file_sidecars_39500000_39999999.conf": No such file or directory (os error 2) reth bsc mainnet

### ISSUE THREAD

**Issue by thejoven** [bnb-chain/reth-snapshots#3]
```
~/mnt/mainnet/data/temp_save/static_files # /root/reth/target/release/bsc-reth node --full --datadir=/root/mnt/mainnet/data/temp_save --datadir.static_files=/root/mnt/mainnet/data/temp_save/static_files --chain=bsc --http --http.api="eth, net, txpool, web3, rpc" --http.addr 0.0.0.0 --log.file.directory /root/mnt/mainnet/
2024-10-25T06:37:53.501879Z  INFO Initialized tracing, debug log directory: /root/mnt/mainnet/bsc
2024-10-25T06:37:53.503984Z  INFO Starting reth version="1.0.5 (231d4be5)"
2024-10-25T06:37:53.504652Z  INFO Opening database path="/root/mnt/mainnet/data/temp_save/db"
2024-10-25T06:37:53.527516Z  INFO Configuration loaded path="/root/mnt/mainnet/data/temp_save/reth.toml"
2024-10-25T06:37:53.534529Z  INFO Verifying storage consistency.
2024-10-25T06:37:53.535947Z  INFO Unwinding static file segment. segment=Transactions from=42988451 to=0
2024-10-25T06:37:53.536575Z  INFO Unwinding static file segment. segment=Receipts from=42988451 to=0
2024-10-25T06:37:53.537186Z  INFO Unwinding static file segment. segment=Sidecars from=40499999 to=0
2024-10-25T06:37:53.537541Z ERROR shutting down due to error
Error: nippy jar error: failed to open file "/root/mnt/mainnet/data/temp_save/static_files/static_file_sidecars_39500000_39999999.conf": No such file or directory (os error 2)

Location:
    /root/reth/crates/node/builder/src/launch/common.rs:420:38
```

The latest downloaded snapshot has encountered a problem of missing files.

**Comment by pythonberg1997** [comment]
Could you show the file list of `/root/mnt/mainnet/data/temp_save/static_files`?

**Comment by unclezoro** [comment]
guess @thejoven is using a different directory, can you give a relative path?

**Comment by slarkbehappy** [comment]
Hi @thejoven, I initially encountered the same problem, but soon I found out it was caused by my incorrect startup command.

Firstly, please note whether you have downloaded the FullNode snapshot or the ArchiveNode snapshot? The mistake I made was using the FullNode snapshot without adding `--full`.

My complete startup command is:

```
./bsc-reth node \
    --datadir=./datadir \
    --chain=bsc \
    --http \
    --http.api="eth, net, txpool, web3, rpc" \
    --log.file.directory ./datadir/logs 
    --full
```

Compared to this, I will move the `static_files` in `./data/temp_save/` to `./datadir`, then, the remaining `database.version`, `mdbx.dat`, `mdbx.lck` need to be moved to `./datadir/db/`. 

You can try starting the bsc-reth FullNode once without using a snapshot, which will generate the corresponding directory, and then we move the snapshot in. 

In the end, I used the latest snapshot and successfully started synchronization.

**Comment by thejoven** [comment]
> Could you show the file list of `/root/mnt/mainnet/data/temp_save/static_files`?
I confirmed that the directory is indeed missing the static_file_sidecars_39500000_39999999.conf.

@unclezoro @pythonberg1997 - The suggestion is to update the latest snapshot.

The MD5 value of the LZ4 I downloaded does not match c5be7be4defd37788d4acbe1a1fcf67b, so I did not attempt to proceed further.

I no longer use snapshots to sync nodes, I am syncing from scratch, and I have now entered the third stage. Thank you all for your help.
